GET http://localhost:3333/api

###
GET http://localhost:3333/api/user/78/Oleg

###

GET http://localhost:3333/api/test/109

###
GET http://localhost:3333/api/user/second?name=Oleg&age=20

###
POST http://localhost:3333/api/user
Content-Type: application/json

{
    "name":"Alex",
    "email":"alex@gmail.com",
    "age":20,
    "address":{
        "street":"ya444",
        "house":10
    }
}


###
GET http://localhost:3333/api/test/10?title=mytestdata

###
POST http://localhost:3333/product
Content-Type: application/json

{
    "title":"milk",
    "price":63
}

###
GET http://localhost:3333/product

###
GET http://localhost:3333/product/1

###
PATCH http://localhost:3333/product/2
Content-Type: application/json

{
    "price":67
}

### 
DELETE http://localhost:3333/product/1
